services:
  - type: web
    name: it_asset_final_beta
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    runtime: python-3.11.9
